# Generated by Django 4.2.3 on 2023-07-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default=True, max_length=250)),
                ('dob', models.CharField(default=True, max_length=20)),
                ('age', models.IntegerField(default=True)),
                ('gender', models.CharField(default=True, max_length=10)),
                ('phn', models.IntegerField(default=True)),
                ('mail', models.EmailField(default=True, max_length=254, unique=True)),
                ('dist', models.CharField(default=True, max_length=50)),
                ('branch', models.CharField(default=True, max_length=50)),
                ('acc', models.CharField(default=True, max_length=50)),
                ('material', models.BooleanField(default=False)),
            ],
        ),
    ]
